### ISSUE TITLE
利用規約が改正民法に対応していない可能性

### ISSUE THREAD

**Issue by sakarush** [zenn-dev/zenn-docs#2]
## 💡 要点

利用規約 第14条の内容が改正民法と照らして問題がある可能性があります。

## ☹️ 問題点

改正民法においては、ユーザーにとって不利益な変更でなくても、十分な猶予期間を持ち、周知しなければいけません。
また、ユーザーにとって不利益な変更については、個別に同意を取る必要があり、一方的な変更は無効化される恐れがあります。

## 🙂 解決法 

例えば以下のような条文に変更します。（一例です）
```
運営者は、必要と判断し、かつ以下に当てはまる場合には、運営者の裁量により利用規約を変更することが出来ます。

1. 利用規約の変更が、ユーザーの一般の利益に適合するとき。
2. 利用規約の変更が、契約をした目的に反せず、かつ、変更の必要性、変更後の内容の相当性、変更の内容その他の変更に係る事情に照らして合理的なものであるとき。

ただし、前項の定めに従い利用規約を変更する際は、十分な猶予期間を持って本サイトやメールにより利用者に周知するものとします。
```
ユーザーに不利益な条文の変更は別途同意を取る必要があります。

## 📝 その他注意点
私は法律の専門家ではないので、責任を負えません。
ユーザーにとって不利益な変更とは思えませんので、猶予期間と周知の後に変更するだけで十分だと思われます。

詳しくは記事に書かせて頂きました。
https://zenn.dev/sr/articles/d3535be6ea8aca3e2691

**Comment by catnose99** [comment]
遅くなりすみません。
この度顧問弁護士さんをつけまして、上記の点に関しても相談のうえ必要であれば改訂を行います。
手続きに関しても弁護士さんにお願いすることにします。
連休ということもあり対応にしばらく時間がかかると思います。
今しばらくお待ちください。

**Comment by catnose99** [comment]
変更したらこちらに追記します。
一度クローズさせていただきます。
