### ISSUE TITLE
画像の誤り

### ISSUE THREAD

**Issue by staticWagomU** [zenn-dev/zenn-docs#32]
https://github.com/zenn-dev/zenn-docs/blob/f665d4e85d29b51a5b8d55987d162f07dc146f94/books/how-to-create-book/viewer.md?plain=1#L17

となっていますが、下記のボタンではないでしょうか？
![image](https://user-images.githubusercontent.com/34824645/162118202-9c1ac21f-2b07-4224-af66-d3402898d694.png)

**Comment by tannerjohn65** [comment]
本件、ご指摘いただきありがとうございます。上記につきまして、修正いたしましたのでCloseします。
引き続き、よろしくお願いいたします。
