### ISSUE TITLE
Zennの本にある画面左の目次を非表示にすることはできますか？

### ISSUE THREAD

**Issue by grocio** [zenn-dev/zenn-docs#41]
自分で調べられなかっただけですと申し訳ありませんが、Zennで本を開いた時の画面左にある目次を非表示にできますか（トグルできますか）？

Jupyter Bookには画面左上にハンバーガーボタンがあり、目次の表示・非表示をトグルできます。
[https://jupyterbook.org/en/stable/intro.html](https://jupyterbook.org/en/stable/intro.html)

細かい点ですが、特にチャプターが長い場合などチャプターの内容に集中したい際には目次を非表示できると良いのかなと思います。

**Comment by cm-igarashi-ryosuke** [comment]
@grocio 

> Zennで本を開いた時の画面左にある目次を非表示にできますか（トグルできますか）？

現状では、ブラウザの横幅をある程度狭くすると隠れるようにはなっていますが、
求めていることは幅に関係なく非表示にしたいということですよね。

類似するIssueがこちらにありました。
https://github.com/zenn-dev/zenn-community/issues/386

トグルでの折りたたみも検討したいと思います。

こちらのリポジトリはzenn公式アカウントのドキュメント管理用リポジトリなので、クローズさせていただきます。

**Comment by grocio** [comment]
> 求めていることは幅に関係なく非表示にしたいということですよね。
その通りです。類似するIssueについても教えていただきありがとうございます。
ご検討いただけましたら幸いです。
