### ISSUE TITLE
2024年1月22日改定の利用規約に仮文言が残っている

### ISSUE THREAD

**Issue by bicstone** [zenn-dev/zenn-docs#78]
@cm-igarashi-ryosuke 
お世話になっております。外部から失礼いたします。
Publication Proのリリースおめでとうございます。

2024年1月22日改定の利用規約に `2023年＿月＿日まで` という文言が残っていたのですが、こちら `2024年1月22日まで` が正しいかと思います。

https://github.com/zenn-dev/zenn-docs/blob/a0ac4eec25fa03143cd0e6e449a3e501757b107f/pages/terms-publication.md?plain=1#L100

https://github.com/zenn-dev/zenn-docs/pull/75/files?w=1#diff-d94edd2ea76c1c06466a0b74f3e0f1486846b5249407978fd0cb1e767b2a2a9bR100

お手数をおかけしますが、ご確認よろしくお願いいたします。

**Comment by cm-igarashi-ryosuke** [comment]
@bicstone ご指摘いただき感謝いたします。該当箇所を修正いたしました。

**Comment by bicstone** [comment]
修正確認しました。
迅速なご対応ありがとうございます！
